import { createUseStyles } from "react-jss";

export const useServicesStyles = createUseStyles({
  app: {
    backgroundColor: "black",
    minHeight: "265vh",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",

    color: "white",
  },
  neonBackground: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    background: "linear-gradient(45deg, rgb(5, 2, 80), black, rgb(5, 2, 80))",
    backgroundSize: "400% 400%",
    animation: "$neonAnimation 15s ease-in-out infinite",
  },
  pageTitle: {
    position: "absolute",
    top: -900,
    left: -220,
    position: "relative",
    padding: "20px",
    fontSize: "45px",
    color: "white",
    textDecoration: "none",
    borderBottom: "4px solid transparent",
    transition: "border-color 0.3s ease",
    "&:hover": {
      borderColor: "royalblue",
    },
  },
  buttonUp1: {
    padding: "1px 1px",
    backgroundColor: "whith",
    color: "#white",
    fontStyle: "Trattatello, fantasy",
    fontWeight: "bold",
    border: "none",
    borderRadius: "230px",
    position: "absolute",
    top: "95%",
    left: "73%",
    fontSize: "18px",
    cursor: "pointer",
    transition: "background-color 0.3s ease",
    "&:hover": {
      backgroundColor: "#0056b3",
    },
  },
  buttonUp2: {
    padding: "1px 1px",
    backgroundColor: "whith",
    color: "#white",
    fontStyle: "Trattatello, fantasy",
    fontWeight: "bold",
    border: "none",
    borderRadius: "230px",
    position: "absolute",
    top: "103%",
    left: "72%",
    fontSize: "18px",
    cursor: "pointer",
    transition: "background-color 0.3s ease",
    "&:hover": {
      backgroundColor: "#0056b3",
    },
  },
  buttonUp3: {
    padding: "1px 1px",
    backgroundColor: "whith",
    color: "#white",
    fontStyle: "Trattatello, fantasy",
    fontWeight: "bold",
    border: "none",
    borderRadius: "230px",
    position: "absolute",
    top: "133%",
    left: "72%",
    fontSize: "18px",
    cursor: "pointer",
    transition: "background-color 0.3s ease",
    "&:hover": {
      backgroundColor: "#0056b3",
    },
  },
  buttonUp4: {
    padding: "1px 1px",
    backgroundColor: "whith",
    color: "#white",
    fontStyle: "Trattatello, fantasy",
    fontWeight: "bold",
    border: "none",
    borderRadius: "230px",
    position: "absolute",
    top: "167%",
    left: "72%",
    fontSize: "18px",
    cursor: "pointer",
    transition: "background-color 0.3s ease",
    "&:hover": {
      backgroundColor: "#0056b3",
    },
  },
  buttonUp5: {
    padding: "1px 1px",
    backgroundColor: "whith",
    color: "#white",
    fontStyle: "Trattatello, fantasy",
    fontWeight: "bold",
    border: "none",
    borderRadius: "230px",
    position: "absolute",
    top: "200%",
    left: "72%",
    fontSize: "18px",
    cursor: "pointer",
    transition: "background-color 0.3s ease",
    "&:hover": {
      backgroundColor: "#0056b3",
    },
  },
  buttonUp6: {
    padding: "1px 1px",
    backgroundColor: "whith",
    color: "#white",
    fontStyle: "Trattatello, fantasy",
    fontWeight: "bold",
    border: "none",
    borderRadius: "230px",
    position: "absolute",
    top: "234%",
    left: "72%",
    fontSize: "18px",
    cursor: "pointer",
    transition: "background-color 0.3s ease",
    "&:hover": {
      backgroundColor: "#0056b3",
    },
  },
  ptag: {
    fontSize: "43px",
    fontStyle: "italic",
    position: "absolute",
    top: "70%",
    left: "1%",
  },
  img: { width: "56px", height: "50px" },
});
